# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_7', '0002_auto_20171114_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='ttl',
            field=models.CharField(default='-', max_length=400),
        ),
    ]
